### ISSUE TITLE
前辈，不好意思，打扰您一下

### ISSUE THREAD

**Issue by Run2948** [bidianqing/SSO.Sample#1]
我把项目迁出到本地不知道，运行时发现启动不了，然后就看了项目服务器启动时是用的外部主机，http:/domain.dev。像这种情况，如果是在本地IIS或者IIS Express怎么运行出效果呢？

**Comment by bidianqing** [comment]
改成不使用外部主机，同时修改web.config

`<forms name="sso" protection="All" path="/" domain="localhost"/>`

**Comment by bidianqing** [comment]
将三个项目分别部署到IIS，填写主机名，修改hosts文件
